### PR TITLE
[PR-1] Add tests for Production Report with date and device filtering, URL parameters, and PDF download

### PR DESCRIPTION
**Pull request by Romanussss**
**Changelog:**
- **Date Filtering Tests (UI & URL):** Added tests to validate date range selection through both UI inputs and URL parameters.
- **Device Filtering Tests:** Enhanced tests to verify device checkbox filtering functionality, covering both UI toggles and URL parameter handling.
- **PDF Download Test:** Implemented a test to confirm successful PDF download and validate the filename format.
- **ID Updates:** Assigned unique IDs to key elements (inputs, filters, buttons) for improved test targeting and reliability.

### CODE REVIEW

**Comment by TheCodingCanal** [comment]
hey, did you finish this project? just wanted to touch base so I'm not missing anyone. thanks, jesse

**Comment by Romanussss** [comment]
Hi

It was me who had the pr, it was a mistake on my part as I pushed in the
wrong repo the first time.

Unfortunately I could only complete the first part with the tests. The
Dev-Ops task I could not complete as i had an error I could not figure out
in time so I did not think it was enough tasks completed to even send
anything to you.

Thanks for the chance, it was an interesting experience.

Best Regards,
Vlad

**Comment by TheCodingCanal** [comment]
Hey Vlad, 
The deadline is just a rough guideline so that people aren't taking forever.
Want to have an interview and talk about what you got done and what hurdles you ran into?
If so, can you reply to my email?
Cheers, Jesse

**Comment by Romanussss** [comment]
Hey

Of course, im free for an interview, im in the EEST time zone, so i am
available anywhere from 9:00 AM -- 8:00 PM during the week. Let me know
what time works for you.

Best regards,
Vlad

**Comment by TheCodingCanal** [comment]
Hey Vlad,
Can you send me an email please. Then I can send you my schedule link.
Jesse

**Pull request closed without merging**
